### ISSUE TITLE
Weather.js crash 

### ISSUE THREAD

**Issue by gannonprudhomme** [gannonprudhomme/Desktop-Control-Tablet#67]
Not really sure what went wrong as of now, but the server crashed with this error

```
{ Error: ETIMEDOUT
    at Timeout._onTimeout (C:\Users\Gannon\Dropbox\Public\workspace\workspace_se
rver\node_modules\request\request.js:849:19)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5) code: 'ETIMEDOUT', connect: true }
C:\Users\Gannon\Dropbox\Public\workspace\workspace_server\routes\weather.js:19
            var data = d[0]
                        ^

TypeError: Cannot read property '0' of undefined
    at C:\Users\Gannon\Dropbox\Public\workspace\workspace_server\routes\weather.
js:19:25
    at Request._callback (C:\Users\Gannon\Dropbox\Public\workspace\workspace_ser
ver\node_modules\weather-js\index.js:42:41)
    at self.callback (C:\Users\Gannon\Dropbox\Public\workspace\workspace_server\
node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Timeout._onTimeout (C:\Users\Gannon\Dropbox\Public\workspace\workspace_se
rver\node_modules\request\request.js:852:16)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
```

**Comment by gannonprudhomme** [comment]
Also getting a `cannot read current of undefined` from weather-js
