### ISSUE TITLE
Unknown crash

### ISSUE THREAD

**Issue by gannonprudhomme** [gannonprudhomme/Desktop-Control-Tablet#69]
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error [ERR_SOCKET_CANNOT_SEND]: Unable to send data
    at Socket.onListenError (dgram.js:379:22)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at state.handle.lookup (dgram.js:294:14)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
Emitted 'error' event at:
    at Socket.onListenError (dgram.js:379:8)
    at Object.onceWrapper (events.js:273:13)
    [... lines matching original stack trace ...]
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

**Comment by gannonprudhomme** [comment]
Happened again on launch, still am not sure why. Could probs debug by adding console logs in every socket call

**Comment by gannonprudhomme** [comment]
Eh closing this, no way I can reproduce this at this point
